image: python:3.12

stages:
  - install
  - test
  - build
  - release

variables:
  UV_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/uv"

cache:
  paths:
    - ${UV_CACHE_DIR}

before_script:
  - pip install uv

install_dependencies:
  stage: install
  script:
    - uv sync --all-extras

run_tests:
  stage: test
  script:
    - uv sync --all-extras
    - uv run pytest --cov=src/gemini_gitlab_workflow --cov-report=xml:coverage.xml tests/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

build_project:
  stage: build
  script:
    - uv sync --all-extras
    - uv run pyinstaller ggw.spec
  artifacts:
    paths:
      - dist/ggw

create_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Creating release for tag $CI_COMMIT_TAG"
    - release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG --assets-link "{"name":"ggw","url":"${CI_PROJECT_URL}/-/jobs/$(cat ${CI_JOB_ID})/artifacts/file/dist/ggw"}"
  dependencies:
    - build_project
